# -*- coding: utf-8 -*-
"""Sistem Manajemen Kamar Hotel Berbasis Nomor Ruangan_BST Benary Search Tree Dasar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuAPXNbGe8919PoQfKXKoC_DHQF0tRsj
"""

class NodeKamar:
    def __init__(self, nomor_kamar, tipe_kamar, status):
        self.nomor_kamar = nomor_kamar
        self.tipe_kamar = tipe_kamar
        self.status = status
        self.left = None
        self.right = None

class SistemHotelBST:
    def __init__(self):
        self.root = None


    def _insert_kamar(self, root, nomor_kamar, tipe_kamar, status):
        if root is None:
            return NodeKamar(nomor_kamar, tipe_kamar, status)


        if nomor_kamar < root.nomor_kamar:
            root.left = self._insert_kamar(root.left, nomor_kamar, tipe_kamar, status)
        elif nomor_kamar > root.nomor_kamar:
            root.right = self._insert_kamar(root.right, nomor_kamar, tipe_kamar, status)
        else:
            print(f"\n[Gagal] Kamar nomor {nomor_kamar} sudah terdaftar sebelumnya!")
        return root

    def tambah_kamar(self, nomor_kamar, tipe_kamar, status):
        self.root = self._insert_kamar(self.root, nomor_kamar, tipe_kamar, status)
        print(f"[Sukses] Kamar nomor {nomor_kamar} ({tipe_kamar}) berhasil ditambahkan ke sistem.")


    def _search_kamar(self, root, nomor_kamar):
        if root is None or root.nomor_kamar == nomor_kamar:
            return root

        if nomor_kamar < root.nomor_kamar:
            return self._search_kamar(root.left, nomor_kamar)
        return self._search_kamar(root.right, nomor_kamar)

    def cari_kamar(self, nomor_kamar):
        hasil = self._search_kamar(self.root, nomor_kamar)
        if hasil:
            print(f"\n--- Data Kamar Ditemukan ---")
            print(f"Nomor Kamar : {hasil.nomor_kamar}")
            print(f"Tipe Kamar  : {hasil.tipe_kamar}")
            print(f"Status      : {hasil.status}")
        else:
            print(f"\n[Informasi] Kamar nomor {nomor_kamar} tidak terdaftar di sistem hotel ini.")


    def _inorder_display(self, root):
        if root is not None:
            self._inorder_display(root.left)
            print(f"| {root.nomor_kamar:<12} | {root.tipe_kamar:<20} | {root.status:<15} |")
            self._inorder_display(root.right)

    def tampilkan_semua_kamar(self):
        if self.root is None:
            print("\n[Informasi] Belum ada kamar yang didaftarkan di sistem hotel.")
            return
        print("\n" + "="*57)
        print(f"| {'NOMOR KAMAR':<12} | {'TIPE KAMAR':<20} | {'STATUS':<15} |")
        print("="*57)
        self._inorder_display(self.root)
        print("="*57)

def main():
    hotel = SistemHotelBST()

    while True:
        print("\n=== SISTEM MANAJEMEN DATA KAMAR HOTEL (BST) ===")
        print("1. Daftarkan Kamar Baru")
        print("2. Cari Detail Kamar (Berdasarkan Nomor)")
        print("3. Tampilkan Semua Kamar (Urutan Nomor Terkecil)")
        print("4. Keluar")

        try:
            pilihan = int(input("Pilih Menu: "))
        except ValueError:
            print("Input tidak valid! Masukkan angka menu.")
            continue

        if pilihan == 1:
            try:
                nomor = int(input("Masukkan Nomor Kamar (Angka): "))
                tipe = input("Masukkan Tipe Kamar (Standard/Deluxe/Suite): ")
                status = input("Masukkan Status Kamar (Kosong/Terisi): ")
                hotel.tambah_kamar(nomor, tipe, status)
            except ValueError:
                print("Input Nomor Kamar harus berupa angka!")

        elif pilihan == 2:
            try:
                nomor_cari = int(input("Masukkan nomor kamar yang dicari: "))
                hotel.cari_kamar(nomor_cari)
            except ValueError:
                print("Input Nomor Kamar harus berupa angka!")

        elif pilihan == 3:
            hotel.tampilkan_semua_kamar()

        elif pilihan == 4:
            print("Program selesai. Terima kasih!")
            break
        else:
            print("Pilihan menu tidak tersedia!")

if __name__ == "__main__":
    main()